app_name: sendpulse
server:
  address: ":8080"
  mode: dev
database:
  dsn: "postgres://postgres:postgres@localhost:5432/sendpulse?sslmode=disable"
messaging:
  interval: 5s
  batch_size: 10
  max_retries: 2
  retry_delay: 2s
  enabled: true
webhook:
  url: "https://webhook.site/24e00d25-dcc0-46fe-97f2-5a14026de18f"
